spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: cos
    password: qweasd
    driver-class-name: org.postgresql.Driver
    

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#        
#logging.level:
#  org.hibernate.SQL: debug